service: edge-lambda-redirect

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}

functions:
  redirect-sample:
    handler: index.handler
    name: ${self:provider.stage}-cloudfront-redirect-latest